### ISSUE TITLE
Dockerfile no longer works after ffmpeg update

### ISSUE THREAD

**Issue by llamafilm** [li-zhi/vmaf-notebook#1]
The `docker build` command fails because it's looking for a folder called ffmpeg-git-20220622-amd64-static.  The archive at https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz has since been updated to ffmpeg-git-20220722-amd64-static.
As a quick and dirty fix, you could just change the Dockerfile line to `mv ffmpeg-git-* ffmpeg && \`.

**Comment by li-zhi** [comment]
Thanks for the tip. let me upate it.
